scheme: "RosÃ© Pine"
author: "Emilia Dunfelt <sayhi@dunfelt.se>"
base00: "191724"
base01: "1f1d2e"
base02: "26233a"
base03: "555169"
base04: "6e6a86"
base05: "e0def4"
base06: "f0f0f3"
base07: "c5c3ce"
base08: "e2e1e7"
base09: "eb6f92"
base0A: "f6c177"
base0B: "ebbcba"
base0C: "31748f"
base0D: "9ccfd8"
base0E: "c4a7e7"
base0F: "e5e5e5"
