scheme: "RosÃ© Pine Moon"
author: "Emilia Dunfelt <sayhi@dunfelt.se>"
base00: "232136"
base01: "2a273f"
base02: "393552"
base03: "59546d"
base04: "817c9c"
base05: "e0def4"
base06: "f5f5f7"
base07: "d9d7e1"
base08: "ecebf0"
base09: "eb6f92"
base0A: "f6c177"
base0B: "ea9a97"
base0C: "3e8fb0"
base0D: "9ccfd8"
base0E: "c4a7e7"
base0F: "b9b9bc"
