scheme: "RosÃ© Pine Dawn"
author: "Emilia Dunfelt <sayhi@dunfelt.se>"
base00: "faf4ed"
base01: "fffaf3"
base02: "f2e9de"
base03: "9893a5"
base04: "6e6a86"
base05: "575279"
base06: "555169"
base07: "26233a"
base08: "1f1d2e"
base09: "b4637a"
base0A: "ea9d34"
base0B: "d7827e"
base0C: "286983"
base0D: "56949f"
base0E: "907aa9"
base0F: "c5c3ce"
